### ISSUE TITLE
Maven plugin default phase

### ISSUE THREAD

**Issue by baurchanu** [OpenAPITools/openapi-style-validator#138]
Hi, thank you for the maven plugin!

Why did you choose the verify phase as default?
Imho the validation phase is more appropriate, cause the vast majority of use cases is validation before compilation with the openapi-generator-maven-plugin.

Copypaste from [Maven Build Lifecycle](https://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#a-build-lifecycle-is-made-up-of-phases):
- validate - validate the project is correct and all necessary information is available
- compile - compile the source code of the project
- ...
- verify - run any checks on results of integration tests to ensure quality criteria are met

**Comment by JFCote** [comment]
Hi @baurchanu,

That makes a lot of sense. @jmini is the one who worked on both the gradle and maven plugin so I'm tagging him here and let's wait for his answer.

Thanks!

**Comment by jmini** [comment]
I do not have a strong opinion here.

I selected "verify", because it is more in the same phase than unit-test execution. 
The `openapi-style-validator` is ensuring that quality criteria are met.

But of course if you depend from `openapi-style-validator` to validate that everything is correct and that you can continue with the build, you need to do it earlier.

I think it can be changed.

**Comment by baurchanu** [comment]
Unit tests run during the "test" phase immediately after the "compile", because it's impossible to run unit tests without a compilation. We don't need to compile sources for OAS validations, therefore I suggest to change the phase for failing ASAP.
