### ISSUE TITLE
Verify that path parameters are in path.

### ISSUE THREAD

**Issue by gervaisb** [OpenAPITools/openapi-style-validator#177]
It should be great to validate that a path parameter is effectively into the operation path. 

Given this specification:

    paths:
      /resource/{identifier}:
        get:
          parameters:
            - in: path
              name: id
              required: true

The validation should fail because the path parameter `id` is not found in the path. 

As a bonus, the validation should also ensure that path parameters are required, as stated in the specification.

**Comment by JFCote** [comment]
Hi @gervaisb,

Once I have a little time, I will need to check if the basic `validate` function from [OpenAPI Generator](https://github.com/OpenAPITools/openapi-generator) is already taking care of this validation. This seems to me like a basic "specification validation" instead of a "style validation".

If you have time, you can check and let me know. Otherwise, I should be able to check for this in a couple of weeks, very busy right now.

Thanks!

**Comment by gervaisb** [comment]
Indeed, the OpenAPI Generator do that kind of validation. However, I did not wanted to use another tool to validate my specifications. But I guess that you don't want to spend your valuable time on that kind of improvement. 

Thanks for your work.
