### ISSUE TITLE
Implement Sonarqube rules

### ISSUE THREAD

**Issue by michaelsonnleitner** [OpenAPITools/openapi-style-validator#73]
You have implemented a CLI for usage. Great! - but the findings sould be available in a Sonarqube installation. I suggest to implement [Sonar rules](https://docs.sonarqube.org/display/PLUG/Writing+Custom+Java+Rules+101#WritingCustomJavaRules101-Gettingstarted) 

I have found [following sonar rules](https://github.com/societe-generale/sonar-openapi) implementation. But this has rather less rules (9). In my opinion your rules are a great idea and sould be available via sonar!

What do you mean?

**Comment by JFCote** [comment]
Hi @michaelsonnleitner !

To be honest, I don't even know what is Sonarqube and what it is used for. If you want, you could work on a PR to propose your change and I will gladly consider it.

Thanks!

**Comment by jmini** [comment]
@JFCote: SonarQube is a famous open-source tool used for Code Quality improvements https://www.sonarqube.org/
It is a dashboard where you collect reports from static codes checkers. You can assign them to somebody or mark them as false positive.

---

@michaelsonnleitner: are you sure that we need to extend write a Custom Java Rules? This tool is checking for issues in `json` and `yaml` files. It has nothing to do with Java (just the checker is written in Java).

**Comment by michaelsonnleitner** [comment]
of course. sonar is currently analysing 27+ languages (https://www.sonarqube.org/features/multi-languages/)

**Comment by JFCote** [comment]
@michaelsonnleitner Since my first answer above, I've installed Sonarlint on all my project and I'm in the process of installing sonarqube at the office.

I'm not sure how `openapi-style-validator` can be integrated. OpenAPI is not a language, it is one of the million of uses of `.yaml`. There is no good or bad decision in the style validation, that's why we added configuration. If course, we have the default values which could be what we inject in the sonarlint for example.

I will need to read the documentation on this. Of course, if you can help us with the integration, please let us know.

**Comment by michaelsonnleitner** [comment]
there are several [other rules](https://github.com/societe-generale/sg-openapi-plugin) based on [sonar-openapi](https://github.com/societe-generale/sonar-openapi) so I decided to switch to that plugin

**Comment by JFCote** [comment]
@michaelsonnleitner Thanks for the information. We'll see if we can integrate with sonar in the future. Thanks for the idea :)
