### ISSUE TITLE
Travis build doesn't pass

### ISSUE THREAD

**Issue by JFCote** [OpenAPITools/openapi-style-validator#75]
It seems we have a "deploy" build that keeps failing on Travis.
The "build" badge on the main page show "failing".

Here is the error:

```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':cli:publishMavenJavaPublicationToSonatypeRepository'.
> Failed to publish publication 'mavenJava' to repository 'sonatype'
   > Invalid publication 'mavenJava': multiple artifacts with the identical extension and classifier ('jar', 'null').
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings
BUILD FAILED in 4s
12 actionable tasks: 9 executed, 3 up-to-date
The command "./gradlew publishToSonatype -PsonatypeUser=$SONATYPE_USER -PsonatypePassword=$SONATYPE_PASSWORD" exited with 1.
Done. Your build exited with 1.

```

**Comment by jmini** [comment]
The issue is that the `cli` project is producing 2 jars:

* The normal one (as every java project would do)
* The shadowJar jar one that is quite convenient because all dependencies are included inside and you can run it with `java -jar`

When pushing on a maven repo (a distant one) but you see the same failure if you publish to your local maven repository (using `./gradlew publishToMavenLocal`), the 2 jars are creating a conflict.

It seems to me that often the `all` classifier is used for the shadowJar
